


export const Sheet_Header = {
  ar: [
    ' رقم الفرع     ',
    ' أســم الفرع     ',
    '  رقم المنطقة  ',
    '  اسم المنطقة    ',
    ' رقم الوحدة    ',
    ' اسم الوحدة      ',
    ' رقم القسم     ',
    ' اسم القسم       ',
    ' رقم التسلسل  ',
    ' الرقم العام  ',
    'الرقم الخاص   ',
    ' اسم الموظف   ',
    ' رمز مسمى الوظيفة  ',
    ' مسمى الوظيفة  ',
    ' رمز الرتبة الحالية   ',
    ' مسمى الرتبة الحالية  ',
    ' رمز نوع الرتبة الحالية ',
    ' مسمى نوع الرتبة الحالية ',
    ' رمز الرتبة في التشكيل   ',
    ' مسمى الرتبة في التشكيل  ',
    ' رمز نوع الرتبة في التشكيل ',
    ' مسمى نوع الرتبة في التشكيل @'
  ],
  en: [
    'branch_number',
    'branch_name',
    'area_number',
    'area_name',
    'unit_number',
    'unit_name',
    'section_number',
    'section_name',
    'sequence_number',
    'general_number',
    'specific_number',
    'employee_name',
    'job_title_code',
    'job_title_name',
    'current_rank_code',
    'current_rank_name',
    'current_rank_type_code',
    'current_rank_type_name',
    'current_rank_in_commission_code',
    'current_rank_in_commission_name',
    'current_rank_type_in_commission_code',
    'current_rank_type_in_commission_name',
  ],
}

